### ISSUE TITLE
Bug : Tensorflow step should reuse "context" variable to load its checkpoint. 

### ISSUE THREAD

**Issue by jeromebedard12** [Neuraxio/Neuraxle-TensorFlow#11]
https://github.com/Neuraxio/Neuraxle-TensorFlow/blob/e25f2d1e84b0f7ee23b45043656b681bd8b24e5e/neuraxle_tensorflow/tensorflow_v2.py#L203

**Comment by alexbrillant** [comment]
@jeromebedard12 thanks a lot for pointing that out ! fixed here : #12
