### ISSUE TITLE
code issue/bug?

### ISSUE THREAD

**Issue by littlegirl6688** [Neuraxio/Neuraxle-TensorFlow#16]
Hi Guillaume,

Thank you for sharing these codes! When i am trying to run your code, i always met following issue( i did not change anything, but jut re-run your code). Any ideas what should I do?  i am using neuraxle==0.5.2. Thank you !

 AttributeError                            Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/neuraxle/base.py in apply(self, method, ra, *args, **kwargs)
    718         try:
--> 719             results = _method(*kargs, **ra.kwargs)
    720             if not isinstance(results, RecursiveDict):

~/.local/lib/python3.6/site-packages/neuraxle/base.py in _set_hyperparams(self, hyperparams)
   1434         hyperparams = HyperparameterSamples(hyperparams).to_flat()
-> 1435         self.hyperparams = hyperparams if len(hyperparams) > 0 else self.hyperparams
   1436         return self.hyperparams

**AttributeError: 'Tensorflow2ModelStep' object has no attribute 'hyperparams'**
~/.local/lib/python3.6/site-packages/neuraxle/base.py in set_hyperparams(self, hyperparams)
   1427             :func:`_HasChildrenMixin._set_train`
   1428         """
-> 1429         self.apply(method='_set_hyperparams', hyperparams=HyperparameterSamples(hyperparams).to_flat())
   1430         return self
   1431 

~/.local/lib/python3.6/site-packages/neuraxle/base.py in apply(self, method, ra, *args, **kwargs)
    723             return results
    724         except Exception as err:
--> 725             print('{}: Failed to apply method {}.'.format(self.name, method))
    726             print(traceback.format_stack())
    727             raise err

**AttributeError: 'Tensorflow2ModelStep' object has no attribute 'name'**

**Comment by alexbrillant** [comment]
@littlegirl6688 I have fixed this issue already. let me open a pull request.

**Comment by alexbrillant** [comment]
@littlegirl6688 I just fixed it. it should be fine with neuraxle-tensorflow==0.1.2 :) have a good day

**Comment by littlegirl6688** [comment]
thank you so much!
