### ISSUE TITLE
Feature: make saver simple

### ISSUE THREAD

**Issue by guillaume-chevalier** [Neuraxio/Neuraxle-TensorFlow#2]
Pseudocode with probably the wrong function names, but you get it: 

```
class TF1Saver: 
    def save(self, step): 
        stripped_graphs = dict()
        stripped_sessions = dict()

        for k, v in step.__dict__:

            if isinstance(v, graph): 
                self.stripped_graphs[k] = v
                step = self._strip_graph(step, k)

            elif isinstance(v, session): 
                self.stripped_sessions[k] = v
                step = self._strip_session(step, k)

        self._save_stripped_things(stripped_graphs, stripped_sessions)
        return step
```

**Comment by alexbrillant** [comment]
In my opinion, a tensorflow step should only have one session, and one graph.

**Comment by guillaume-chevalier** [comment]
@alexbrillant That would seem right, I agree

**Comment by guillaume-chevalier** [comment]
We could have it set to always self.sess and self.graph

**Comment by adriangb** [comment]
FYI you will now be able to serialize tensorflow models using pickle. It uses SavedModel under the hood, so it will be compatible across TensorFlow releases.

**Comment by guillaume-chevalier** [comment]
@adriangb Interesting. That probably means that we could check tensorflow's version to see if we need custom savers before setting one. Do you know if this change to tensorflow will work with joblib?

**Comment by adriangb** [comment]
Yes, it should. TLDR is that `tf.Keras.Model.__reduce__` is implemented and just "redirects" to TensorFlow's SavedModel.
The following works:

```python
import joblib
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Input

inp = Input(shape=(1,))
out = Dense(1, activation='sigmoid')(inp)
model = Model([inp], [out])
model.compile(loss='binary_crossentropy')
model.fit([[1]], [1])  # note that fit or build need to be called before pickling

joblib.dump(model, "test.pkl")
print(open("test.pkl", "rb").read())
```
